const GET_WEATHER = 'GET_WEATHER_FOR_CITY';
const GET_WEATHER_START = 'GET_WEATHER_START';
const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS';
const GET_WEATHER_ERROR = 'GET_WEATHER_ERROR';


export default {
    GET_WEATHER,
    GET_WEATHER_START,
    GET_WEATHER_SUCCESS,
    GET_WEATHER_ERROR
}

